CREATE TABLE ADDRESS_MASTER
AS
SELECT DISTINCT COUNTRY_ID, STATE_PROVINCE,CITY
FROM LOCATIONS;

CREATE TABLE ADDRESSES 
(
  ADDRESS_LINE_1 VARCHAR2(100 BYTE) 
, ADDRESS_LINE_2 VARCHAR2(100 BYTE) 
, COUNTRY_ID VARCHAR2(20 BYTE) 
, STATE_PROVINCE VARCHAR2(100 BYTE) 
, CITY VARCHAR2(100 BYTE) 
) 