package viewObjects.client;

import oracle.jbo.client.remote.ViewUsageImpl;

import viewObjects.common.EmployeesVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 09 00:20:26 CDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesVOClient extends ViewUsageImpl implements EmployeesVO {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesVOClient() {
    }

    public void clearJobVC() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"clearJobVC",null,null);
        return;
    }

    public void dept60VP() {
        Object _ret = getApplicationModuleProxy().riInvokeExportedMethod(this,"dept60VP",null,null);
        return;
    }

    public void setDeptVC(oracle.jbo.domain.Number x) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setDeptVC",new String [] {"oracle.jbo.domain.Number"},new Object[] {x});
        return;
    }

    public void setJobVC(String x) {
        Object _ret =
            getApplicationModuleProxy().riInvokeExportedMethod(this,"setJobVC",new String [] {"java.lang.String"},new Object[] {x});
        return;
    }
}
