package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 28 00:28:16 ADT 2017
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void applyFindByName(String n);
}
