package viewObjects.common;

import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 09 00:20:25 CDT 2017
// ---------------------------------------------------------------------
public interface EmployeesVO extends ViewObject {
    void clearJobVC();

    void dept60VP();

    void setDeptVC(oracle.jbo.domain.Number x);

    void setJobVC(String x);
}
