package model;

import model.common.AppModule;

import oracle.jbo.ViewCriteria;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 28 00:06:28 ADT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for AdCorporateLocationsVO1.
     * @return AdCorporateLocationsVO1
     */
    public ViewObjectImpl getAdCorporateLocationsVO1() {
        return (ViewObjectImpl)findViewObject("AdCorporateLocationsVO1");
    }

    /**
     * Container's getter for EmCorporateProfilesVO1.
     * @return EmCorporateProfilesVO1
     */
    public ViewObjectImpl getEmCorporateProfilesVO1() {
        return (ViewObjectImpl)findViewObject("EmCorporateProfilesVO1");
    }

    /**
     * Container's getter for AdCorporateLocationsVO2.
     * @return AdCorporateLocationsVO2
     */
    public ViewObjectImpl getAdCorporateLocationsVO2() {
        return (ViewObjectImpl)findViewObject("AdCorporateLocationsVO2");
    }

    /**
     * Container's getter for LocationLOV1.
     * @return LocationLOV1
     */
    public LocationLOVImpl getLocationLOV1() {
        return (LocationLOVImpl)findViewObject("LocationLOV1");
    }

    /**
     * Container's getter for CorlocCorproFkLink1.
     * @return CorlocCorproFkLink1
     */
    public ViewLinkImpl getCorlocCorproFkLink1() {
        return (ViewLinkImpl)findViewLink("CorlocCorproFkLink1");
    }
    public void applyFindByName(String n){
        ViewObjectImpl vo = this.getLocationLOV1();
        ViewCriteria vc = vo.getViewCriteria("LocationLOVCriteria");
        vo.setNamedWhereClauseParam("Name1", n);
        vo.applyViewCriteria(vc);
        vo.executeQuery();
    }
}
