package viewObjects;

import oracle.jbo.ViewCriteria;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewCriteriaAdapter;
import oracle.jbo.server.ViewObjectImpl;

import viewObjects.common.EmployeesVO;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 08 23:55:09 CDT 2017
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesVOImpl extends ViewObjectImpl implements EmployeesVO {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesVOImpl() {
    }

    /**
     * Returns the variable value for DeptIdBind.
     * @return variable value for DeptIdBind
     */
    public Number getDeptIdBind() {
        return (Number)ensureVariableManager().getVariableValue("DeptIdBind");
    }

    /**
     * Sets <code>value</code> for variable DeptIdBind.
     * @param value value to bind as DeptIdBind
     */
    public void setDeptIdBind(Number value) {
        ensureVariableManager().setVariableValue("DeptIdBind", value);
    }

    /**
     * Returns the variable value for JobIdBind.
     * @return variable value for JobIdBind
     */
    public String getJobIdBind() {
        return (String)ensureVariableManager().getVariableValue("JobIdBind");
    }

    /**
     * Sets <code>value</code> for variable JobIdBind.
     * @param value value to bind as JobIdBind
     */
    public void setJobIdBind(String value) {
        ensureVariableManager().setVariableValue("JobIdBind", value);
    }
    public void setJobVC(String x){
        ViewCriteria vc = getViewCriteria("InJobViewCriteria");
        vc.resetCriteria();//reset the vc that has been initiated designed time
        setJobIdBind(x);
        applyViewCriteria(vc);
        executeQuery();
    }
    public void setDeptVC(Number x){
        ViewCriteria vc = getViewCriteria("InDeptViewCriteria");
        vc.resetCriteria();
        setDeptIdBind(x);
        applyViewCriteria(vc);
        executeQuery();
    }
    
    public void clearJobVC(){
        removeApplyViewCriteriaName("InJobViewCriteria");
        removeApplyViewCriteriaName("InDeptViewCriteria");
        executeQuery();
    }
    public void dept60VP(){
        ViewCriteria vcd = getViewCriteria("InDeptViewCriteria");
        //ViewCriteria vcj = getViewCriteria("InJobViewCriteria");
        vcd.resetCriteria();
        //vcj.resetCriteria();
        setDeptIdBind(new Number(60));
       // setJobIdBind("AD_VP");
        //applyViewCriteria(vcj);
        applyViewCriteria(vcd,true);
        executeQuery();
    }
    
}
